// <auto-generated />
namespace ProjectManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTeamProjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTeamProjects));
        
        string IMigrationMetadata.Id
        {
            get { return "201708310306508_addTeamProjects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
