//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The current password is incorrect or the new password is invalid. 的本地化字符串。
        /// </summary>
        internal static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Id already registered. 的本地化字符串。
        /// </summary>
        internal static string EmailExixts {
            get {
                return ResourceManager.GetString("EmailExixts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Id already registered. 的本地化字符串。
        /// </summary>
        internal static string EmailExixts1 {
            get {
                return ResourceManager.GetString("EmailExixts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email is required. 的本地化字符串。
        /// </summary>
        internal static string Emailrequired {
            get {
                return ResourceManager.GetString("Emailrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enddate cannot be before Start date. 的本地化字符串。
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entered Date cannot be EndDate  Since the Last Updated Entered Date cannot be EndDate  Since the Last Updated Date is 的本地化字符串。
        /// </summary>
        internal static string EndDateNotValid {
            get {
                return ResourceManager.GetString("EndDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus already exists. 的本地化字符串。
        /// </summary>
        internal static string FocusExists {
            get {
                return ResourceManager.GetString("FocusExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goal already exists. 的本地化字符串。
        /// </summary>
        internal static string GoalExists {
            get {
                return ResourceManager.GetString("GoalExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group already exists. 的本地化字符串。
        /// </summary>
        internal static string GroupExists {
            get {
                return ResourceManager.GetString("GroupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invitation Sent! 的本地化字符串。
        /// </summary>
        internal static string InvitationSent {
            get {
                return ResourceManager.GetString("InvitationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong Username/Password! 的本地化字符串。
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username and Password required! 的本地化字符串。
        /// </summary>
        internal static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Followed Goals 的本地化字符串。
        /// </summary>
        internal static string MyFollowedGoals {
            get {
                return ResourceManager.GetString("MyFollowedGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MyFollowingsGoals 的本地化字符串。
        /// </summary>
        internal static string MyFollowingsGoals {
            get {
                return ResourceManager.GetString("MyFollowingsGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Goals 的本地化字符串。
        /// </summary>
        internal static string MyGoals {
            get {
                return ResourceManager.GetString("MyGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password is required. 的本地化字符串。
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already joined this group. 的本地化字符串。
        /// </summary>
        internal static string PersonJoined {
            get {
                return ResourceManager.GetString("PersonJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already joined this group. 的本地化字符串。
        /// </summary>
        internal static string PersonJoined1 {
            get {
                return ResourceManager.GetString("PersonJoined1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already supporting this goal. 的本地化字符串。
        /// </summary>
        internal static string PersonSupporting {
            get {
                return ResourceManager.GetString("PersonSupporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already supporting this goal. 的本地化字符串。
        /// </summary>
        internal static string PersonSupporting1 {
            get {
                return ResourceManager.GetString("PersonSupporting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popularity 的本地化字符串。
        /// </summary>
        internal static string Popularity {
            get {
                return ResourceManager.GetString("Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required 的本地化字符串。
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 的本地化字符串。
        /// </summary>
        internal static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check your mail to reset password! 的本地化字符串。
        /// </summary>
        internal static string ResetPasswordEmailSent {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entered Date cannot be Start Date  Since the First Updated Date is 的本地化字符串。
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload error. Try again! 的本地化字符串。
        /// </summary>
        internal static string UploadError {
            get {
                return ResourceManager.GetString("UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This email is not registered for any Social Goal users. 的本地化字符串。
        /// </summary>
        internal static string UserDoesntExist {
            get {
                return ResourceManager.GetString("UserDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong Email Id ! 的本地化字符串。
        /// </summary>
        internal static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
    }
}
